---
- name: Create ansible.log
  file:
    path: /var/log/ansible.log
    state: touch
    modification_time: preserve
    access_time: preserve
    mode: '0644'
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"

- name: Install buster-backports
  apt_repository: repo="deb http://ftp.debian.org/debian buster-backports main"
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '10'

- name: Install Ansible from backport
  apt:
    name: ansible
    state: latest
    default_release: buster-backports
    # 86400 seconds = 24 hours
    cache_valid_time: 86400
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '10'

- name: Install necessary Ansible packages
  apt:
    name: ['ansible', 'pass', 'expect', 'python3-pip', "php{{ php_version }}-cli", "php{{ php_version }}-curl"]
    # 86400 seconds = 24 hours
    cache_valid_time: 86400

- name: Install pip packages for Megaphone Ansible
  pip:
    name: linode_api4

- name: Install ansible.cfg
  copy: 
    src: files/ansible.cfg
    dest: "{{ playbook_dir }}/ansible.cfg"
    mode: '0644'
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"

- name: Install gethosts.cfg.php
  copy: 
    src: files/gethosts.cfg.php
    dest: "{{ playbook_dir }}/gethosts.cfg.php"
    mode: '0644'
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"

- name: Add gitea keys to local user known_hosts
  known_hosts:
    name: "[git.megaphonetech.com]:10022"
    key: "{{ inner_item }}"
  loop_control:
    loop_var: inner_item
  with_items:
    - "[git.megaphonetech.com]:10022 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDgNwIe3TBtRHtkwoHL2TG84/f039hgzqVbN0z4sk1UHPZr4rxFinGCGjedzE+adVucqr/gemPnETfashTujcPyZZkwPn2dQNx0HuPHw3H+cqXqKt03fsgPcerqsqvFS509pcblmP5vtJLF4uVgbh6TLmZiObMuiIYe9VTyZSXo67DTt/K6SSgwyUFldqJIJQA+DO1nXoSYSJ4fP1DDPdue0RTL06VtlnUL2w9iHrOgVRY1KqAtpnGRslKx5c3L8+9EBMdJWM1CPK11vkvyf8LnYwuCH4V7w0rVs2QAE9Abm4g4HiE4wql5QJrjCi/cq/1doeY9KXxFb8SOTtZBk5Nn"
    - "[git.megaphonetech.com]:10022 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLuEP2fW8Eycdbeo0XWihr63zj6yCTcCjxh4C4i3c8p2O44mKRjVhxOSSBQQxZNUKeJYAGTuWh+EPW71KADzXv0="
    - "[git.megaphonetech.com]:10022 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJoN1UsqLqucSJo4dSum6Xy2qCrlutDAu3wPdprAL4w"
  become: no

- name: Download the password database
  git:
    repo: "ssh://git@git.megaphonetech.com:10022/megaphone/passwords.git"
    dest: ~/.password-store
  become: no
# TODO: Create authorized_keys
