---
- name: Install buster-backports
  apt_repository: repo="deb http://ftp.debian.org/debian buster-backports main"
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '10'

- name: Install necessary Ansible packages
  apt:
    name: ['ansible', 'pass', 'expect', 'python3-pip']
    state: present
    # 86400 seconds = 24 hours
    cache_valid_time: 86400

- name: Install pip packages for Megaphone Ansible
  pip:
    name: linode_api4
